version: '3'

services:
  db:
    image: mysql
    container_name: marvel-sql
    ports: 
      - 3306:3306
    environment:       
      - MYSQL_USER=rique
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=marvel
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
